services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: resume_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro 
  frontend:
    image: ${DOCKER_REGISTRY}/profile-fe:${FE_VERSION}
    restart: unless-stopped
    container_name: resume_frontend
    expose:
      - "3000"
    environment:
      - VITE_API_URL=${BE_URL}
      - VITE_LOGO_PATH=${LOGO_PATH}
      - VITE_BACKGROUND_PATH=${BACKGROUND_PATH}
      - VITE_BANNER_PATH=${BANNER_PATH}
      - VITE_PROFILE_PATH=${PROFILE_PATH}
      - VITE_DEBUG=${DEBUG}
    volumes:
      - ./profile-frontend/public:/app/public
  backend:
    image: ${DOCKER_REGISTRY}/profile-be:${BE_VERSION}
    restart: unless-stopped
    container_name: resume_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - ASSETS_PATH=/app/public/assets
      - ENABLE_LIST_API=${ENABLE_LIST_API}
      - LIST_API_TOKEN=${LIST_API_TOKEN}
    volumes:
      - ./profile-frontend/public:/app/public
  cms-frontend:
    image: ${DOCKER_REGISTRY}/cms-fe:${CMS_FE_VERSION}
    container_name: cms_frontend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - VITE_API_URL=${BE_URL}/cms-api
    depends_on:
      - cms-backend
  cms-backend:
    image: ${DOCKER_REGISTRY}/cms-be:${CMS_BE_VERSION}
    container_name: cms_backend
    restart: unless-stopped
    expose:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    container_name: resume_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
