FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY profile-frontend/package*.json ./
RUN npm install --legacy-peer-deps

# Copy source code
COPY profile-frontend/ ./

EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
